### ISSUE TITLE
unresolved Imports

### ISSUE THREAD

**Issue by SaratAdiraj** [qalingo/qalingo-engine#35]
I'm getting the following issues with unresolved imports:

The import org.hoteia.qalingo.core.domain.ProductBrand_ cannot be resolved
I could not locate ProductBrand_ class. m i missing something?

**Comment by dgosset** [comment]
org.hoteia.qalingo.core.domain.ProductBrand_ is generated classe by an Hibernate plugin.
You can run something like "mvn eclipse:eclipse" to add the target/generated folder in your "project > build path" or change this yourself in your IDE.
The plugin : <artifactId>hibernate-jpamodelgen</artifactId>

**Comment by narender-balauda** [comment]
@dgosset Did you succeeded in setting up the Qalingo ?
If yes, could you guide me how to do that please?

Thanks
