### ISSUE TITLE
compiler error for the cause of encoding.

### ISSUE THREAD

**Issue by yqnetwork** [qalingo/qalingo-engine#37]
org\hoteia\qalingo\core\util\CoreUtil.java:157: 错误: 编码GBK的不可映射字符
stringToReturn = stringToReturn.replaceAll("鈥?", "-");
                                                     ^

This file compile difficult by maven for the encoding. The compiler-plugin in pom.xml didn't  work. My workspace is git bash in win10.

**Comment by dgosset** [comment]
are you in UTF-8?

**Comment by yqnetwork** [comment]
because my environment git bash or cmd all is GBK. I can't specified the mvn cmd as utf-8. 
I haven't find the encoding has be set in the pom.xml. It just be set in the pluginManagement. But it's not be set in any compiler-plugin.
Maybe, I have just not found it.

**Comment by dgosset** [comment]
ok. fixed/pull

**Comment by yqnetwork** [comment]
thanks

**Comment by narender-balauda** [comment]
@yqnetwork Did you succeeded in setting up the Qalingo ?
If yes, could you guide me how to do that please?

Thanks
