### ISSUE TITLE
after run:  mvn clean install -P dev-qalingo -Dskip-setup-mysql=false

### ISSUE THREAD

**Issue by orangeyts** [qalingo/qalingo-engine#39]
`[ERROR] Failed to execute goal on project qalingo-api-core-common: Could not resolve dependencies for project org.hoteia.qalingo:qalingo-api-core-comm
on:jar:0.8.1-SNAPSHOT: Failed to collect dependencies at net.sf.jasperreports:jasperreports:jar:5.5.0 -> com.lowagie:itext:jar:2.1.7.js2: Failed to re
ad artifact descriptor for com.lowagie:itext:jar:2.1.7.js2: Could not transfer artifact com.lowagie:itext:pom:2.1.7.js2 from/to jasperreports (http://
jasperreports.sourceforge.net/maven2): This is usually a temporary error during hostname resolution and means that the local server did not receive a
response from an authoritative server -> [Help 1]`

**Comment by narender-balauda** [comment]
@orangeyts Did you succeeded in setting up the Qalingo ?

**Comment by dgosset** [comment]
Use http://nexus.hoteia.com as your Maven repo.
