### ISSUE TITLE
B2B support

### ISSUE THREAD

**Issue by narender-balauda** [qalingo/qalingo-engine#41]
Is this support B2B also ?

**Comment by dgosset** [comment]
yes B2C/B2B

**Comment by narender-balauda** [comment]
Just need some more info:

Does it supports Sales Orders, Purchase Orders, Memo etc?
Does it support Multiple Vendors ?

**Comment by dgosset** [comment]
It does. Checkout the engine, and take a look at the code entities like cart/order/product*
Was only ecommerce at the beginning, and was refactoring for marketplace
Next refactoring this summer for Spring4/Java8/Ehcache3
