### ISSUE TITLE
How to setup and run B2B App over Intellij

### ISSUE THREAD

**Issue by narender-balauda** [qalingo/qalingo-engine#42]
Hi,

I want to configure your B2B engine over Intellij so that i can see the Admin panel as well as the Store front but i haven't find any information yet.
Do you have any step by step instruction document?

Help would be appreciated.

Thanks

**Comment by narender-balauda** [comment]
How can i setup B2B demo on my local?
Please help.

Thanks in advance

**Comment by dgosset** [comment]
Sorry i don't use Intellij
