### ISSUE TITLE
can not find class like class_

### ISSUE THREAD

**Issue by wsdflink** [qalingo/qalingo-engine#43]
import org.hoteia.qalingo.core.domain.CatalogCategoryMaster_;
import org.hoteia.qalingo.core.domain.CatalogCategoryVirtual_;

i can not find these classes above. can you tell me where they are?

**Comment by dgosset** [comment]
The are generate in "qalingo-api-core-common" (pom.xml line 27) by "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor".
